# docker compose file that launches next.js app and mongodb

version: '3.7'

services:
  app:
    image: node:20
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
    environment:
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - MONGO_URL
      - JWT_SECRET
      - GCLOUD_BUCKET_NAME
      - GCLOUD_PROJECT_ID
      - GCLOUD_CLIENT_EMAIL
      - GCLOUD_PRIVATE_KEY
    depends_on:
      - mongodb
    command: bash -c "cd /app && yarn run dev"
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
