export const frasesBrainUp = [
  "¡Descubre el poder de la lógica con BrainUp! 5 minutos al día, el camino hacia la maestría.",
  "Circuitos lógicos, desafía tu mente y conquista el día. ¡BrainUp te acompaña en la aventura!",
  "En el universo de la digitalidad, BrainUp es tu guía. 5 minutos bastan para iluminar tu trayectoria.",
  "¡Abraza el desafío! Con BrainUp, cada día es una oportunidad para ampliar tu horizonte lógico.",
  "Circuitos como melodía, BrainUp como partitura. ¡Dirige tu aprendizaje en solo 5 minutos!",
  "Descubre la magia detrás de los 1 y 0. ¡Con BrainUp, tu propia alquimia digital en 5 minutos al día!",
  "Cada minuto cuenta, cada circuito enseña. Con BrainUp, transforma 5 minutos en conocimiento puro.",
  "¡Enciende tu mente con BrainUp! Circuitos lógicos, el desafío diario que te llevará a la grandeza.",
  "En el rincón de la lógica, BrainUp es tu mejor compañero. ¡5 minutos diarios para la victoria!",
  "Circuitos como acertijos, BrainUp como la clave. Descifra el misterio en solo 5 minutos cada día.",
  "¡Despierta al ingeniero en ti! BrainUp te invita a construir tu conocimiento, 5 minutos a la vez.",
  "Lógica y diversión, la combinación perfecta. BrainUp convierte cada día en un festival de descubrimientos.",
  "Circuitos, tu nuevo campo de batalla. ¡Conquístalos en 5 minutos diarios con la ayuda de BrainUp!",
  "En el aula de la lógica, BrainUp es tu maestro. ¡5 minutos al día para brillar como un estrella digital!",
  "¡Eleva tu mente! BrainUp te lleva a nuevas alturas en el arte de los circuitos, 5 minutos a la vez.",
  "Circuitos como puzles, BrainUp como la pieza faltante. Completa el cuadro en solo 5 minutos al día.",
  "En el camino de los bytes, BrainUp es tu brújula. Navega hacia el conocimiento en solo 5 minutos diarios.",
  "¡Conquista tu propio reino lógico con BrainUp! 5 minutos al día y serás el soberano del circuito.",
  "Circuitos como destellos de creatividad. BrainUp, la chispa que enciende tu genio en 5 minutos.",
  "En el teatro de la lógica, BrainUp es tu obra maestra. ¡Deslumbra al mundo con 5 minutos diarios!",
  "¡Atrévete al desafío! BrainUp te invita a un viaje de descubrimiento en circuitos lógicos, solo 5 minutos al día.",
  "Circuitos como escalones hacia el conocimiento. Con BrainUp, sube un peldaño cada día en solo 5 minutos.",
  "En el jardín de la lógica, BrainUp es tu semilla de sabiduría. ¡Cultiva tu mente en 5 minutos diarios!",
  "¡Desata el poder de la lógica con BrainUp! 5 minutos al día para liberar tu genio interior.",
  "Circuitos como constelaciones en el cielo digital. BrainUp, tu mapa para explorarlas en 5 minutos diarios.",
  "En el laboratorio de la mente, BrainUp es tu experimento exitoso. Descubre el secreto en 5 minutos al día.",
  "¡Conviértete en el director de tu propia sinfonía lógica! BrainUp te da la partitura en 5 minutos diarios.",
  "Circuitos como senderos hacia la comprensión. Sigue el camino con BrainUp, solo 5 minutos al día.",
  "En el desfile de la lógica, BrainUp es tu carro alegórico. ¡Desfila hacia el conocimiento en 5 minutos diarios!",
  "¡Despierta al mago de la lógica que llevas dentro! Con BrainUp, conjura la sabiduría en 5 minutos diarios.",
  "Circuitos como piezas de un rompecabezas. BrainUp, tu guía para resolverlo en solo 5 minutos al día.",
  "En el teatro de la mente, BrainUp es tu actor principal. ¡Brilla en escena con 5 minutos de circuitos!",
  "¡Eleva tu IQ digital! BrainUp te desafía a conquistar los circuitos en solo 5 minutos al día.",
  "Circuitos como acertijos esperando a ser resueltos. Con BrainUp, descubre la respuesta en 5 minutos diarios.",
  "En el océano de la información, BrainUp es tu brújula. Navega hacia el conocimiento en solo 5 minutos al día.",
  "¡Construye tu imperio lógico con BrainUp! 5 minutos al día, el secreto para un reinado digital.",
  "Circuitos como notas en la sinfonía de la lógica. Con BrainUp, compón tu melodía en 5 minutos diarios.",
  "En el museo de la mente, BrainUp es tu obra maestra. ¡Añade pinceladas de conocimiento en 5 minutos al día!",
  "¡Descubre el arte de la lógica con BrainUp! 5 minutos diarios para esculpir tu propia obra maestra.",
  "Circuitos como escalones hacia el conocimiento. Sube un peldaño cada día con la ayuda de BrainUp, en solo 5 minutos.",
  "En el gimnasio cerebral, BrainUp es tu entrenador personal. ¡Fortalece tu mente en solo 5 minutos al día!",
  "¡Despierta al explorador lógico que llevas dentro! BrainUp te invita a una aventura en circuitos, solo 5 minutos al día.",
  "Circuitos como hilos de la maraña lógica. Con BrainUp, teje tu propia historia en solo 5 minutos diarios.",
  "En la biblioteca del conocimiento, BrainUp es tu libro de referencia. ¡Lee una página cada día en solo 5 minutos!",
  "¡Haz de cada día un día de descubrimientos lógicos! BrainUp te guía en la travesía, solo 5 minutos al día.",
  "Circuitos como destellos de creatividad. Con BrainUp, ilumina tu mente en solo 5 minutos diarios.",
  "En el laboratorio lógico, BrainUp es tu fórmula del éxito. ¡Descúbrelo en solo 5 minutos al día!",
  "¡Eleva tu mente al siguiente nivel con BrainUp! 5 minutos diarios para desafiar los límites de la lógica.",
  "Circuitos como piezas de un rompecabezas cósmico. Con BrainUp, ensambla tu comprensión en solo 5 minutos al día.",
  "En el festival de la lógica, BrainUp es tu invitación VIP. ¡Únete a la celebración en solo 5 minutos diarios!",
  "¡Despierta al alquimista lógico que hay en ti! BrainUp te invita a transformar conocimiento en solo 5 minutos al día.",
  "Con BrainUp, la lógica es tu danza, 5 minutos al día, ¡y serás una bonanza!",
  "Circuitos y chistes, una mezcla divina. Con BrainUp, la risa y el aprendizaje se combinan.",
  "En el mundo lógico, BrainUp es la joya. 5 minutos al día, ¡y serás un genio a toda hora!",
  "¡Despierta tu mente, no seas un sonámbulo! Con BrainUp, en 5 minutos, ¡serás un lógico zombi!",
  "Circuitos y bromas, una combinación sabrosa. Con BrainUp, el aprendizaje se vuelve jocoso.",
  "En el reino lógico, BrainUp es el rey. 5 minutos al día, ¡y serás el héroe del bodegón de circuitos!",
  "¡Rima y razón, con BrainUp la conexión! 5 minutos al día, ¡y dominarás la lógica como canción!",
  "Circuitos y chispeante humor. Con BrainUp, ¡la risa es el mejor motor!",
  "En el libro de la lógica, BrainUp es el capítulo divertido. 5 minutos al día, ¡y serás el autor preferido!",
  "¡Desata tu ingenio, sé un mago lógico! Con BrainUp, en 5 minutos, ¡serás el Houdini del circuito!",
  "Circuitos y carcajadas, una pareja infalible. Con BrainUp, ¡la diversión es inquebrantable!",
  "En el teatro de la mente, BrainUp es la comedia. 5 minutos al día, ¡y la lógica se vuelve tragedia!",
  "¡Atrévete al desafío, no seas tímido! Con BrainUp, en 5 minutos, ¡serás el maestro del circuito!",
  "Circuitos y chistes, una alianza potente. Con BrainUp, ¡la risa es tu mejor instrumento!",
  "En el festival lógico, BrainUp es el payaso. 5 minutos al día, ¡y el conocimiento es tu abrazo!",
  "¡Ríete de la confusión, domina la lógica con pasión! Con BrainUp, en 5 minutos, ¡serás un campeón!",
  "Circuitos y bromas, un combo ganador. Con BrainUp, ¡la diversión es el motor!",
  "En el circo lógico, BrainUp es el malabarista. 5 minutos al día, ¡y la lógica es tu artista!",
  "¡Con BrainUp, la lógica es una melodía! 5 minutos al día, ¡y serás una sinfonía!",
  "Circuitos y risas, un dúo incomparable. Con BrainUp, ¡la lógica es inquebrantable!",
  "En el juego de la lógica, BrainUp es el comodín. 5 minutos al día, ¡y el circuito será tu jardín!",
  "¡Despierta al cómico lógico que hay en ti! Con BrainUp, en 5 minutos, ¡la risa será tu aliada fiel!",
  "Circuitos y cuentos, una mezcla encantada. Con BrainUp, ¡la historia lógica es tu morada!",
  "En el circo de la mente, BrainUp es el domador. 5 minutos al día, ¡y la lógica será tu amor!",
  "¡Con BrainUp, la lógica es tu poesía! 5 minutos al día, ¡y serás una estrella en la vía!",
];
